-- metatables in lua provide operator overloading for tables
-- they are in-built meta methods in metatables, similar to dunder methods of python, that can be used to describe the behaviour of tables

-- METAMETHODS:
-- __index()
-- __newindex()
-- __add()
-- __sub()
-- __mul()
-- __concat()
-- __call()
-- __tostring()
